language: objective-c
osx_image: xcode7.3
cache:
  bundler: true
  directories:
  - vendor/bundle
  - Pods
before_install:
  - export LANG=en_US.UTF-8
  - brew tap homebrew/bundle
  - brew bundle
install:
  - bundle install --without development --deployment --jobs=3 --retry=3
  - bundle exec pod install --no-repo-update
  - carthage bootstrap --no-use-binaries --platform ios
script:
  - bundle exec scan
  - xctool -workspace QuickTableViewController.xcworkspace -scheme Example -sdk iphonesimulator clean build
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - make coverage
notifications:
  email: false
