language: objective-c
osx_image: xcode7.3
cache:
  bundler: true
  directories:
  - vendor/bundle
  - Pods
before_install:
  - export LANG=en_US.UTF-8
  - brew tap homebrew/bundle
  - brew bundle
install:
  - bundle install --without development --deployment --jobs=3 --retry=3
  - bundle exec pod install --no-repo-update
  - carthage bootstrap --no-use-binaries --platform ios
script:
  - set -o pipefail && xcodebuild -project QuickTableViewController.xcodeproj -scheme QuickTableViewController-iOS -sdk iphonesimulator -destination "name=iPhone 6,OS=latest" -enableCodeCoverage YES clean test GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c
  - xctool -workspace QuickTableViewController.xcworkspace -scheme Example -sdk iphonesimulator clean build
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bundle exec rake coverage
notifications:
  email: false
